# Copyright (C) 2025  A. Iooss
# SPDX-License-Identifier: CC0-1.0
# Modified by Pwnzer0tt1

[package]
name = "suricata-filedata-postgres-output"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "filedata_postgres_output"

[dependencies]
env_logger = { version = "0.11.8", default-features = false }
log = "0.4.27"
diesel = { version = "2.2.0", features = ["postgres"] }
diesel_migrations = "2.2.0"
dotenvy = "0.15"
chrono = "0.4.41"
