# Copyright (C) 2024  ANSSI
# SPDX-License-Identifier: CC0-1.0

# Modifications
# Copyright (C) 2025 Pwnzer0tt1
# This file has been modified from the original version.
# Licensed under GPL-3.0

name: digger

services:
  suricata:
    image: ghcr.io/pwnzer0tt1/digger-suricata
    build: ./suricata
    volumes:
      - "./input_pcaps:/input_pcaps:rw"
      - "./suricata/rules:/suricata/rules:ro"
      - "./suricata/output:/suricata/output:rw"
      - "./config:/config:rw"

    # Mode B: capture interface (fast, requires root on vulnbox and in Docker)
    # Drastically reduces ingest delay, but requires to setup traffic mirroring
    # between the vulnbox game interface and a team server.
    command: -i tun5
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    depends_on:
      - postgres

  webapp:
    image: ghcr.io/pwnzer0tt1/digger-webapp
    build: ./webapp
    restart: always
    volumes:
      - "./input_pcaps:/input_pcaps:ro" # remove to prevent users from downloading pcaps
      - "./suricata/output:/suricata/output:ro"
    ports:
      - 0.0.0.0:8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:18-alpine3.23
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      
  grafana:
    image: ghcr.io/pwnzer0tt1/digger-grafana
    build: ./grafana
    restart: always
    ports:
      - "8001:3000"
    depends_on:
      - postgres

volumes:
  pgdata: