# Copyright (C) 2024  ANSSI
# SPDX-License-Identifier: CC0-1.0

# Modifications
# Copyright (C) 2025 Pwnzer0tt1
# This file has been modified from the original version.
# Licensed under GPL-3.0

[workspace]
resolver = "2"
members = [
    "suricata-eve-postgres-output",
    "suricata-filedata-postgres-output",
    "suricata-stream-postgres-output"
]
