# Copyright (C) 2024  ANSSI
# SPDX-License-Identifier: CC0-1.0

# Modifications
# Copyright (C) 2025 Pwnzer0tt1
# This file has been modified from the original version.
# Licensed under GPL-3.0

[package]
name = "suricata-eve-postgres-output"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "eve_postgres_output"

[dependencies]
database = { path = "../database" }
env_logger = { version = "0.11.8", default-features = false }
log = "0.4.27"
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15"
chrono = "0.4.41"
suricata-sys = "8.0.3"