{
 "title": "Home",
 "time": { "from": "2026-02-27T22:55:10.000Z", "to": "2026-02-27T23:08:22.000Z" },
 "panels": [
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT data, to_timestamp(\"timestamp\" / 1000000) FROM stats ORDER BY \"timestamp\" DESC LIMIT 100;"
    }
   ]
  },
  {
   "title": "Packet size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT to_timestamp(\"timestamp\" / 1000000), data FROM stats ORDER BY \"timestamp\" DESC LIMIT 100 "
    }
   ]
  },
  {
   "title": "Total traffic captured",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT data FROM stats ORDER BY \"timestamp\" DESC LIMIT 100 "
    }
   ]
  },
  {
   "title": "Decoder issues",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT to_timestamp(\"timestamp\" / 1000000), data FROM stats ORDER BY \"timestamp\" DESC LIMIT 100;"
    }
   ]
  },
  {
   "title": "Protocols",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT to_timestamp(\"timestamp\" / 1000000), data FROM stats ORDER BY \"timestamp\" DESC LIMIT 100;"
    }
   ]
  },
  {
   "title": "Alerts count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT data FROM stats ORDER BY \"timestamp\" DESC LIMIT 100 "
    }
   ]
  },
  {
   "title": "Flows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT to_timestamp(\"timestamp\" / 1000000), data FROM stats ORDER BY \"timestamp\" DESC LIMIT 100;"
    }
   ]
  },
  {
   "title": "TCP sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT to_timestamp(\"timestamp\" / 1000000), data FROM stats ORDER BY \"timestamp\" DESC LIMIT 100;"
    }
   ]
  }
 ]
}